version: "3"

services:
  app:
    container_name: app
    depends_on: ["db"]
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_USER: rinha
      POSTGRES_DB: rinha

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080